%\VignetteEngine{knitr}
%\VignetteIndexEntry{HUPO 2011 poster: pRoloc -- A unifying bioinformatics framework for organelle proteomics}
%\VignetteKeywords{bioinformatics, organelle proteomics, mass spectrometry, HUPO, poster}

\documentclass[10pt]{article}
\begin{document}


\begin{document}
This vignette is a stub. The poster is only available in pdf.

<<session>>=
sessionInfo()
@

\end{document}
