// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmvtCpp
SEXP dmvtCpp(arma::mat X_, arma::vec mu_, arma::mat sigma_, double df_, bool log_, unsigned int ncores_, bool isChol_);
RcppExport SEXP _pRoloc_dmvtCpp(SEXP X_SEXP, SEXP mu_SEXP, SEXP sigma_SEXP, SEXP df_SEXP, SEXP log_SEXP, SEXP ncores_SEXP, SEXP isChol_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_(mu_SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_(sigma_SEXP);
    Rcpp::traits::input_parameter< double >::type df_(df_SEXP);
    Rcpp::traits::input_parameter< bool >::type log_(log_SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ncores_(ncores_SEXP);
    Rcpp::traits::input_parameter< bool >::type isChol_(isChol_SEXP);
    rcpp_result_gen = Rcpp::wrap(dmvtCpp(X_, mu_, sigma_, df_, log_, ncores_, isChol_));
    return rcpp_result_gen;
END_RCPP
}
// dmvt_log_batch_consistent
arma::vec dmvt_log_batch_consistent(const arma::mat& X, const arma::rowvec& mu, const arma::mat& Sigma, const double df);
RcppExport SEXP _pRoloc_dmvt_log_batch_consistent(SEXP XSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvt_log_batch_consistent(X, mu, Sigma, df));
    return rcpp_result_gen;
END_RCPP
}
// dmvt_log_row_multi_consistent
arma::vec dmvt_log_row_multi_consistent(const arma::rowvec& x, const arma::mat& MU, const List& SIGMA_list, const arma::vec& df);
RcppExport SEXP _pRoloc_dmvt_log_row_multi_consistent(SEXP xSEXP, SEXP MUSEXP, SEXP SIGMA_listSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< const List& >::type SIGMA_list(SIGMA_listSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvt_log_row_multi_consistent(x, MU, SIGMA_list, df));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP C_setOfOnePerturbation(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_pRoloc_dmvtCpp", (DL_FUNC) &_pRoloc_dmvtCpp, 7},
    {"_pRoloc_dmvt_log_batch_consistent", (DL_FUNC) &_pRoloc_dmvt_log_batch_consistent, 4},
    {"_pRoloc_dmvt_log_row_multi_consistent", (DL_FUNC) &_pRoloc_dmvt_log_row_multi_consistent, 4},
    {"C_setOfOnePerturbation", (DL_FUNC) &C_setOfOnePerturbation, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pRoloc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
