// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmvtCpp
SEXP dmvtCpp(arma::mat X_, arma::vec mu_, arma::mat sigma_, double df_, bool log_, unsigned int ncores_, bool isChol_);
RcppExport SEXP _pRoloc_dmvtCpp(SEXP X_SEXP, SEXP mu_SEXP, SEXP sigma_SEXP, SEXP df_SEXP, SEXP log_SEXP, SEXP ncores_SEXP, SEXP isChol_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_(mu_SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_(sigma_SEXP);
    Rcpp::traits::input_parameter< double >::type df_(df_SEXP);
    Rcpp::traits::input_parameter< bool >::type log_(log_SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ncores_(ncores_SEXP);
    Rcpp::traits::input_parameter< bool >::type isChol_(isChol_SEXP);
    rcpp_result_gen = Rcpp::wrap(dmvtCpp(X_, mu_, sigma_, df_, log_, ncores_, isChol_));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP C_setOfOnePerturbation(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_pRoloc_dmvtCpp", (DL_FUNC) &_pRoloc_dmvtCpp, 7},
    {"C_setOfOnePerturbation", (DL_FUNC) &C_setOfOnePerturbation, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pRoloc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
