<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>A transfer learning algorithm for spatial proteomics • pRoloc</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="A transfer learning algorithm for spatial proteomics">
<meta property="og:description" content="pRoloc">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    

    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">pRoloc</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.31.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/v01-pRoloc-tutorial.html">Using pRoloc for spatial proteomics data analysis</a>
    </li>
    <li>
      <a href="../articles/v02-pRoloc-ml.html">Machine learning techniques available in pRoloc</a>
    </li>
    <li>
      <a href="../articles/v03-pRoloc-bayesian.html">Bayesian Analysis of Spatial Proteomics data using pRoloc</a>
    </li>
    <li>
      <a href="../articles/v04-pRoloc-goannotations.html">Annotating spatial proteomics data</a>
    </li>
    <li>
      <a href="../articles/v05-pRoloc-transfer-learning.html">A transfer learning algorithm for spatial proteomics</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/lgatto/pRoloc/" class="external-link">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="v05-pRoloc-transfer-learning_files/header-attrs-2.7/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>A transfer learning algorithm for spatial proteomics</h1>
                        <h4 data-toc-skip class="author">Lisa M. Breckels</h4>
            <address class="author_afil">
      Computational Proteomics Unit, Cambridge, UK<br><h4 data-toc-skip class="author">Laurent Gatto</h4>
            <address class="author_afil">
      de Duve Institute, UCLouvain, Belgium<br><small class="dont-index">Source: <a href="https://github.com/lgatto/pRoloc/blob/master/vignettes/v05-pRoloc-transfer-learning.Rmd" class="external-link"><code>vignettes/v05-pRoloc-transfer-learning.Rmd</code></a></small>
      <div class="hidden name"><code>v05-pRoloc-transfer-learning.Rmd</code></div>

    </address>
</address>
</div>

    
        <div class="abstract">
      <p class="abstract">Abstract</p>
      <p>This vignette illustrates the application of a <em>transfer learning</em> algorithm to assign proteins to sub-cellular localisations. The <em>knntlClassification</em> algorithm combines <em>primary</em> experimental spatial proteomics data (LOPIT, PCP, etc.) and an <em>auxiliary</em> data set (for example binary data based on Gene Ontology terms) to improve the sub-cellular assignment given an optimal combination of these data sources.</p>
    </div>
    
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function() {
  document.querySelector("h1").className = "title";
});
</script><script type="text/javascript">
document.addEventListener("DOMContentLoaded", function() {
  var links = document.links;  
  for (var i = 0, linksLength = links.length; i < linksLength; i++)
    if (links[i].hostname != window.location.hostname)
      links[i].target = '_blank';
});
</script><div id="sec:intro" class="section level1">
<h1 class="hasAnchor">
<a href="#sec:intro" class="anchor" aria-hidden="true"></a>Introduction</h1>
<p>Our main data source to study protein sub-cellular localisation are high-throughput mass spectrometry-based experiments such as LOPIT, PCP and similar designs (see <span class="citation">(Gatto et al. 2010)</span> for an general introduction). Recent optimised experiments result in high quality data enabling the identification of over 6000 proteins and discriminate numerous sub-cellular and sub-organellar niches <span class="citation">(Christoforou et al. 2016)</span>. Supervised and semi-supervised machine learning algorithms can be applied to assign thousands of proteins to annotated sub-cellular niches <span class="citation">(Lisa M. Breckels et al. 2013, Gatto:2014)</span> (see also the <em>pRoloc-tutorial</em> vignette). These data constitute our main source for protein localisation and are termed thereafter <em>primary</em> data.</p>
<p>There are other sources of data about sub-cellular localisation of proteins, such as the Gene Ontology <span class="citation">(Ashburner et al. 2000)</span> (in particular the cellular compartment name space), quantitative features derived from protein sequences (such as pseudo amino acid composition) or the Human Protein Atlas <span class="citation">(Uhlen et al. 2010)</span> to cite a few. These data, while not optimised to a specific system at hand and, in the case of annotation feature, not as reliable as our experimental data, constitute an invaluable, often plentiful source of <em>auxiliary</em> information.</p>
<p>The aim of a <em>transfer learning</em> algorithm is to combine different sources of data to improve overall classification. In particular, the goal is to support/complement the primary target domain (experimental data) with auxiliary data (annotation) features without compromising the integrity of our primary data. In this vignette, we describe the application of transfer learning algorithms for the localisation of proteins from the <em><a href="https://bioconductor.org/packages/3.13/pRoloc" class="external-link">pRoloc</a></em> package, as described in</p>
<blockquote>
<p>Breckels LM, Holden S, Wonjar D, Mulvey CM, Christoforou A, Groen A, Trotter MW, Kohlbacker O, Lilley KS and Gatto L (2016). <em>Learning from heterogeneous data sources: an application in spatial proteomics</em>. PLoS Comput Biol 13;12(5):e1004920. doi: <a href="http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004920" class="external-link">10.1371/journal.pcbi.1004920</a>.</p>
</blockquote>
<p>Two algorithms were developed: a transfer learning algorithm based on the <span class="math inline">\(k\)</span>-nearest neighbour classifier, coined kNN-TL hereafter, described in section @ref(sec:knntl), and one based on the support vector machine algorithm, termed SVM-TL, described in section @ref(sec:svmtl).</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/lgatto/pRoloc" class="external-link">"pRoloc"</a></span><span class="op">)</span></code></pre></div>
</div>
<div id="sec:aux" class="section level1">
<h1 class="hasAnchor">
<a href="#sec:aux" class="anchor" aria-hidden="true"></a>Preparing the auxiliary data</h1>
<div id="sec:goaux" class="section level2">
<h2 class="hasAnchor">
<a href="#sec:goaux" class="anchor" aria-hidden="true"></a>The Gene Ontology</h2>
<p>The auxiliary data is prepared from the primary data’s features. All the GO terms associated to these features are retrieved and used to create a binary matrix where a one (zero) at position <span class="math inline">\((i,j)\)</span> indicates that term <span class="math inline">\(j\)</span> has (not) been used to annotate feature <span class="math inline">\(i\)</span>.</p>
<p>The GO terms are retrieved from an appropriate repository using the <em><a href="https://bioconductor.org/packages/3.13/biomaRt" class="external-link">biomaRt</a></em> package. The specific Biomart repository and query will depend on the species under study and the type of features. The first step is to prepare annotation parameters that will enable to perform the query. The <em><a href="https://bioconductor.org/packages/3.13/pRoloc" class="external-link">pRoloc</a></em> package provides a dedicated infrastructure to set up the query to the annotation resource and prepare the GO data for subsequent analyses. This infrastructure is composed of:</p>
<ol style="list-style-type: decimal">
<li>define the annotation parameters based on the species and feature types;</li>
<li>query the resource defined in (1) to retrieve relevant terms and use the terms to prepare the auxiliary data.</li>
</ol>
<p>We will demonstrate these steps using a LOPIT experiment on Human Embryonic Kidney (HEK293T) fibroblast cells <span class="citation">(Lisa M. Breckels et al. 2013)</span>, available and documented in the <em><a href="https://bioconductor.org/packages/3.13/pRolocdata" class="external-link">pRolocdata</a></em> experiment package as <code>andy2011</code>.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/lgatto/pRolocdata" class="external-link">"pRolocdata"</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">andy2011</span><span class="op">)</span></code></pre></div>
<div id="sec:ap" class="section level3">
<h3 class="hasAnchor">
<a href="#sec:ap" class="anchor" aria-hidden="true"></a>Preparing the query parameters</h3>
<p>The query parameters are stored as <em>AnnotationParams</em> objects that are created with the <em>setAnnotationParams</em> function. The function will present a first menu with 486. Once the species has been selected, a set of possible identifier types is displayed.</p>
<div class="figure">
<img src="Figures/ap12.png" id="fig:apgui" alt=""><p class="caption">Selecting species (left) and feature type (right) to create an <code>AnnotationParams</code> instance for the human <code>andy2011</code> data.</p>
</div>
<p>It is also possible to pass patterns to match against the species (<code>"Human genes"</code>) and feature type (<code>"UniProtKB/Swiss-prot ID"</code>).</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ap</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/AnnotationParams-class.html">setAnnotationParams</a></span><span class="op">(</span>inputs <span class="op">=</span>
                              <span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"Human genes"</span>,
                                <span class="st">"UniProtKB/Swiss-Prot ID"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## Using species Human genes (GRCh38.p13)</code></pre>
<pre><code>## Using feature type UniProtKB/Swiss-Prot ID(s) [e.g. A0A024RBG1]</code></pre>
<pre><code>## Connecting to Biomart...</code></pre>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ap</span></code></pre></div>
<pre><code>## Object of class "AnnotationParams"
##  Using the 'ENSEMBL_MART_ENSEMBL' BioMart database
##  Using the 'hsapiens_gene_ensembl' dataset
##  Using 'uniprotswissprot' as filter
##  Created on Sat May  1 09:31:34 2021</code></pre>
<p>The <em>setAnnotationParams</em> function automatically sets the annotation parameters globally so that the <code>ap</code> object does not need to be explicitly set later on. The default parameters can be retrieved with <em>getAnnotationParams</em>.</p>
</div>
<div id="sec:auxgo" class="section level3">
<h3 class="hasAnchor">
<a href="#sec:auxgo" class="anchor" aria-hidden="true"></a>Preparing the auxiliary data from the GO ontology</h3>
<p>The feature names of the <code>andy2011</code> data are UniProt identifiers, as defined in the <code>ap</code> accession parameters.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">andy2011</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureNames.html" class="external-link">featureNames</a></span><span class="op">(</span><span class="va">andy2011</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "O00767" "P51648" "Q2TAA5" "Q9UKV5" "Q12797" "P16615"</code></pre>
<p>The <em>makeGoSet</em> function takes an <em>MSnSet</em> class (from which the feature names will be extracted) or, directly a vector of characters containing the feature names of interest to retrieve the associated GO terms and construct an auxiliary <code>MSnSet</code>. By default, it downloads <em>cellular component</em> terms and does not do any filtering on the terms evidence codes (see the <em>makeGoSet</em> manual for details). Unless passed as argument, the default, globally set <em>AnnotationParams</em> are used to define the Biomart server and the query.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">andygoset</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/makeGoSet.html">makeGoSet</a></span><span class="op">(</span><span class="va">andy2011</span><span class="op">)</span>
<span class="va">andygoset</span></code></pre></div>
<pre><code>## MSnSet (storageMode: lockedEnvironment)
## assayData: 1371 features, 884 samples 
##   element names: exprs 
## protocolData: none
## phenoData: none
## featureData
##   featureNames: O00767 P51648 ... O75312 (1371 total)
##   fvarLabels: Accession.No. Protein.Description ...
##     UniProtKB.entry.name (10 total)
##   fvarMetadata: labelDescription
## experimentData: use 'experimentData(object)'
## Annotation:  
## - - - Processing information - - -
## Constructed GO set using cellular_component namespace [Sat May  1 09:31:37 2021] 
##  MSnbase version: 2.17.7</code></pre>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/exprs.html" class="external-link">exprs</a></span><span class="op">(</span><span class="va">andygoset</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">7</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">4</span><span class="op">]</span></code></pre></div>
<pre><code>##        GO:0016020 GO:0016021 GO:0005783 GO:0005789
## O00767          1          1          1          1
## P51648          1          1          1          1
## Q2TAA5          1          1          1          1
## Q9UKV5          1          1          1          1
## Q12797          1          1          1          1
## P16615          1          1          1          1
## Q96SQ9          1          0          1          1</code></pre>
<p>We now have a primary data set, composed of 1371 protein quantitative profiles for 8 fractions along the density gradient and an auxiliary data set for 884 cellular compartment GO terms for the same 1371 features.</p>
</div>
<div id="sec:annotrepro" class="section level3">
<h3 class="hasAnchor">
<a href="#sec:annotrepro" class="anchor" aria-hidden="true"></a>A note on reproducibility</h3>
<p>The generation of the auxiliary data relies on specific Biomart server <em>Mart</em> instances in the <em>AnnotationParams</em> class and the actual query to the server to obtain the GO terms associated with the features. The utilisation of online servers, which undergo regular updates, does not guarantee reproducibility of feature/term association over time. It is recommended to save and store the <em>AnnotationParams</em> and auxiliary <em>MSnSet</em> instances. Alternatively, it is possible to use other Bioconductor infrastructure, such as specific organism annotations and the <em><a href="https://bioconductor.org/packages/3.13/GO.db" class="external-link">GO.db</a></em> package to use specific versioned (and thus traceable) annotations.</p>
</div>
</div>
<div id="sec:hpaaux" class="section level2">
<h2 class="hasAnchor">
<a href="#sec:hpaaux" class="anchor" aria-hidden="true"></a>The Human Protein Atlas</h2>
<p>The feature names of our LOPIT experiment are UniProt identifiers, while the Human Protein Atlas uses Ensembl gene identifiers. This first code chunk matches both identifier types using the Ensembl Biomart server and <code>left_join</code> from the <em><a href="https://CRAN.R-project.org/package=dplyr" class="external-link">dplyr</a></em> package. In this section, we copy the experimental data to <code>andyhpa</code>.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">andyhpa</span> <span class="op">&lt;-</span> <span class="va">andy2011</span>
<span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fvarLabels</a></span><span class="op">(</span><span class="va">andyhpa</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">"accession"</span> <span class="co">## for left_join matching</span>
<span class="co">## convert protein accession numbers to ensembl gene identifiers</span>

<span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st">"biomaRt"</span><span class="op">)</span>
<span class="va">mart</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/biomaRt/man/useMart.html" class="external-link">useMart</a></span><span class="op">(</span><span class="st">"ensembl"</span>, dataset <span class="op">=</span> <span class="st">"hsapiens_gene_ensembl"</span><span class="op">)</span>

<span class="va">filter</span> <span class="op">&lt;-</span> <span class="st">"uniprotswissprot"</span>
<span class="va">attrib</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"uniprot_gn_symbol"</span>, <span class="st">"uniprotswissprot"</span>, <span class="st">"ensembl_gene_id"</span><span class="op">)</span>
<span class="va">bm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/biomaRt/man/getBM.html" class="external-link">getBM</a></span><span class="op">(</span>attributes <span class="op">=</span> <span class="va">attrib</span>,
            filters <span class="op">=</span> <span class="va">filter</span>,
            values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">andyhpa</span><span class="op">)</span><span class="op">[</span>, <span class="st">"accession"</span><span class="op">]</span>,
            mart <span class="op">=</span> <span class="va">mart</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">head</a></span><span class="op">(</span><span class="va">bm</span><span class="op">)</span></code></pre></div>
<pre><code>##   uniprot_gn_symbol uniprotswissprot ensembl_gene_id
## 1             ESYT2           A0FGR8 ENSG00000117868
## 2             ILVBL           A1L0T0 ENSG00000105135
## 3              NBAS           A2RRP1 ENSG00000151779
## 4            MTMR11           A4FU01 ENSG00000014914
## 5           C2orf72           A6NCS6 ENSG00000204128
## 6              RTL1           A6NKG5 ENSG00000254656</code></pre>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## HPA data</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st">"hpar"</span><span class="op">)</span></code></pre></div>
<pre><code>## This is hpar version 1.33.3,
## based on the Human Protein Atlas
##   Version: 20.0
##   Release data: 2020.11.19
##   Ensembl build: 92.38
## See '?hpar' or 'vignette('hpar')' for details.</code></pre>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## using old version for traceability</span>
<span class="fu"><a href="https://rdrr.io/pkg/hpar/man/setHparOptions.html" class="external-link">setHparOptions</a></span><span class="op">(</span>hpadata <span class="op">=</span> <span class="st">"hpaSubcellularLoc14"</span><span class="op">)</span>
<span class="va">hpa</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/hpar/man/getHpa.html" class="external-link">getHpa</a></span><span class="op">(</span><span class="va">bm</span><span class="op">$</span><span class="va">ensembl_gene_id</span><span class="op">)</span>
<span class="va">hpa</span><span class="op">$</span><span class="va">Reliability</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/droplevels.html" class="external-link">droplevels</a></span><span class="op">(</span><span class="va">hpa</span><span class="op">$</span><span class="va">Reliability</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html" class="external-link">colnames</a></span><span class="op">(</span><span class="va">hpa</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">"ensembl_gene_id"</span>

<span class="va">hpa</span> <span class="op">&lt;-</span> <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join</a></span><span class="op">(</span><span class="va">hpa</span>, <span class="va">bm</span><span class="op">)</span></code></pre></div>
<pre><code>## Joining, by = "ensembl_gene_id"</code></pre>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hpa</span> <span class="op">&lt;-</span> <span class="va">hpa</span><span class="op">[</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/duplicated.html" class="external-link">duplicated</a></span><span class="op">(</span><span class="va">hpa</span><span class="op">$</span><span class="va">uniprotswissprot</span><span class="op">)</span>, <span class="op">]</span>

<span class="co">## match HPA/LOPIT</span>
<span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html" class="external-link">colnames</a></span><span class="op">(</span><span class="va">hpa</span><span class="op">)</span><span class="op">[</span><span class="fl">7</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">"accession"</span>
<span class="va">fd</span> <span class="op">&lt;-</span> <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html" class="external-link">left_join</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">andyhpa</span><span class="op">)</span>, <span class="va">hpa</span><span class="op">)</span></code></pre></div>
<pre><code>## Joining, by = "accession"</code></pre>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html" class="external-link">rownames</a></span><span class="op">(</span><span class="va">fd</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureNames.html" class="external-link">featureNames</a></span><span class="op">(</span><span class="va">andyhpa</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">andyhpa</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">fd</span>
<span class="fu"><a href="https://rdrr.io/r/base/stopifnot.html" class="external-link">stopifnot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/methods/validObject.html" class="external-link">validObject</a></span><span class="op">(</span><span class="va">andyhpa</span><span class="op">)</span><span class="op">)</span>

<span class="co">## Let's get rid of features without any hpa data</span>
<span class="va">lopit</span> <span class="op">&lt;-</span> <span class="va">andyhpa</span><span class="op">[</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html" class="external-link">is.na</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">andyhpa</span><span class="op">)</span><span class="op">$</span><span class="va">Main.location</span><span class="op">)</span>, <span class="op">]</span></code></pre></div>
<p>Below, we deparse the multiple ‘;’-delimited locations contained in the Human Protein sub-cellular Atlas, create the auxiliary binary data matrix (only localisations with reliability equal to <em>Supportive</em> are considered; <em>Uncertain</em> assignments are ignored - see <a href="http://www.proteinatlas.org/about/antibody+validation" class="external-link uri">http://www.proteinatlas.org/about/antibody+validation</a> for details) and filter proteins without any localisation data.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## HPA localisation</span>
<span class="va">hpalocs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/character.html" class="external-link">as.character</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">lopit</span><span class="op">)</span><span class="op">$</span><span class="va">Main.location</span><span class="op">)</span>,
             <span class="fu"><a href="https://rdrr.io/r/base/character.html" class="external-link">as.character</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">lopit</span><span class="op">)</span><span class="op">$</span><span class="va">Other.location</span><span class="op">)</span><span class="op">)</span>
<span class="va">hpalocs</span> <span class="op">&lt;-</span> <span class="va">hpalocs</span><span class="op">[</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html" class="external-link">is.na</a></span><span class="op">(</span><span class="va">hpalocs</span><span class="op">)</span><span class="op">]</span>
<span class="va">hpalocs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/strsplit.html" class="external-link">strsplit</a></span><span class="op">(</span><span class="va">hpalocs</span>, <span class="st">";"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="va">makeHpaSet</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">score2</span>, <span class="va">locs</span> <span class="op">=</span> <span class="va">hpalocs</span><span class="op">)</span> <span class="op">{</span>
    <span class="va">hpamat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html" class="external-link">matrix</a></span><span class="op">(</span><span class="fl">0</span>, ncol <span class="op">=</span> <span class="fu"><a href="https://lgatto.github.io/MSnbase/reference/pSet-class.html" class="external-link">length</a></span><span class="op">(</span><span class="va">locs</span><span class="op">)</span>, nrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span>
    <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html" class="external-link">colnames</a></span><span class="op">(</span><span class="va">hpamat</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">locs</span>
    <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html" class="external-link">rownames</a></span><span class="op">(</span><span class="va">hpamat</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureNames.html" class="external-link">featureNames</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>
    <span class="kw">for</span>  <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">hpamat</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
        <span class="va">loc</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/strsplit.html" class="external-link">strsplit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/character.html" class="external-link">as.character</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">[</span><span class="va">i</span>, <span class="st">"Main.location"</span><span class="op">]</span><span class="op">)</span>, <span class="st">";"</span><span class="op">)</span><span class="op">)</span>
        <span class="va">loc2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/strsplit.html" class="external-link">strsplit</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/character.html" class="external-link">as.character</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">[</span><span class="va">i</span>, <span class="st">"Other.location"</span><span class="op">]</span><span class="op">)</span>, <span class="st">";"</span><span class="op">)</span><span class="op">)</span>
        <span class="va">score</span> <span class="op">&lt;-</span> <span class="va">score2</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">[</span><span class="va">i</span>, <span class="st">"Reliability"</span><span class="op">]</span><span class="op">]</span>
        <span class="va">hpamat</span><span class="op">[</span><span class="va">i</span>, <span class="va">loc</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">score</span>
        <span class="va">hpamat</span><span class="op">[</span><span class="va">i</span>, <span class="va">loc2</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">score</span>
    <span class="op">}</span>
    <span class="fu"><a href="https://rdrr.io/r/methods/new.html" class="external-link">new</a></span><span class="op">(</span><span class="st">"MSnSet"</span>, exprs <span class="op">=</span> <span class="va">hpamat</span>,
        featureData <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">featureData</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span>
<span class="op">}</span>

<span class="va">hpaset</span> <span class="op">&lt;-</span> <span class="fu">makeHpaSet</span><span class="op">(</span><span class="va">lopit</span>,
                     score2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">c</a></span><span class="op">(</span>Supportive <span class="op">=</span> <span class="fl">1</span>, Uncertain <span class="op">=</span> <span class="fl">0</span><span class="op">)</span><span class="op">)</span>
<span class="va">hpaset</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/filterZeroCols.html">filterZeroRows</a></span><span class="op">(</span><span class="va">hpaset</span><span class="op">)</span></code></pre></div>
<pre><code>## Removing 318 columns with only 0s.</code></pre>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://lgatto.github.io/MSnbase/reference/pSet-class.html" class="external-link">dim</a></span><span class="op">(</span><span class="va">hpaset</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 670  18</code></pre>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/exprs.html" class="external-link">exprs</a></span><span class="op">(</span><span class="va">hpaset</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">6</span>, <span class="fl">200</span><span class="op">)</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">]</span></code></pre></div>
<pre><code>##        Endoplasmic reticulum Cytoplasm Vesicles
## O00767                     1         0        0
## O95302                     0         0        1
## P06493                     0         1        0</code></pre>
</div>
<div id="sec:ppi" class="section level2">
<h2 class="hasAnchor">
<a href="#sec:ppi" class="anchor" aria-hidden="true"></a>Protein-protein interactions</h2>
<p>Protein-protein interaction data can also be used as auxiliary data input to the transfer learning algorithm. Several sources can be used to do so directly from R:</p>
<ul>
<li><p>The <em><a href="https://bioconductor.org/packages/3.13/PSICQUIC" class="external-link">PSICQUIC</a></em> package provides an R interfaces to the HUPO Proteomics Standard Initiative (HUPO-PSI) project, which standardises programmatic access to molecular interaction databases. This approach enables to query great many resources in one go but, as noted in the vignettes, for bulk interactions, it is recommended to directly download databases from individual PSICQUIC providers.</p></li>
<li><p>The <em><a href="https://bioconductor.org/packages/3.13/STRINGdb" class="external-link">STRINGdb</a></em> package provides a direct interface to the STRING protein-protein interactions database. This package can be used to generate a table as the one used below. The exact procedure is described in the <code>STRINGdb</code> vignette and involves mapping the protein identifiers with the <em>map</em> and retrieve the interaction partners with the <em>get_neighbors</em> method.</p></li>
<li><p>Finally, it is possible to use any third-party PPI inference results and adequately prepare these results for transfer learning. Below, we will described this case with PPI data in a tab-delimited format, as retrieved directly from the STRING database.</p></li>
</ul>
<p>Below, we access the PPI spreadsheet file for our test data, that is distributed with the <em><a href="https://bioconductor.org/packages/3.13/pRolocdata" class="external-link">pRolocdata</a></em> package.</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ppif</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/system.file.html" class="external-link">system.file</a></span><span class="op">(</span><span class="st">"extdata/tabdelimited._gHentss2F9k.txt.gz"</span>, package <span class="op">=</span> <span class="st">"pRolocdata"</span><span class="op">)</span>
<span class="va">ppidf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html" class="external-link">read.delim</a></span><span class="op">(</span><span class="va">ppif</span>, header <span class="op">=</span> <span class="cn">TRUE</span>, stringsAsFactors <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">head</a></span><span class="op">(</span><span class="va">ppidf</span><span class="op">)</span></code></pre></div>
<pre><code>##   X.node1  node2 node1_string_id node2_string_id node1_external_id
## 1   NUDT5 IMPDH2         1861432         1850365   ENSP00000419628
## 2    NOP2  RPL23         1858730         1858184   ENSP00000382392
## 3   HSPA4   ENO1         1848476         1843405   ENSP00000302961
## 4   RPS13   DKC1         1862013         1855055   ENSP00000435777
## 5  RPL35A  DDOST         1859718         1856225   ENSP00000393393
## 6  RPL13A   RPS6         1857955         1857216   ENSP00000375730
##   node2_external_id neighborhood fusion cooccurence homology coexpression
## 1   ENSP00000321584        0.000      0           0        0        0.112
## 2   ENSP00000377865        0.000      0           0        0        0.064
## 3   ENSP00000234590        0.000      0           0        0        0.109
## 4   ENSP00000358563        0.462      0           0        0        0.202
## 5   ENSP00000364188        0.000      0           0        0        0.000
## 6   ENSP00000369757        0.000      0           0        0        0.931
##   experimental knowledge textmining combined_score
## 1        0.000       0.0      0.370          0.416
## 2        0.868       0.0      0.000          0.871
## 3        0.222       0.0      0.436          0.575
## 4        0.000       0.0      0.354          0.698
## 5        0.000       0.9      0.265          0.923
## 6        0.419       0.9      0.240          0.996</code></pre>
<p>The file contains 18623 pairwise interactions and the STRING combined interaction score. Below, we create a contingency matrix that uses these scores to encode and weight interactions.</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">uid</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">c</a></span><span class="op">(</span><span class="va">ppidf</span><span class="op">$</span><span class="va">X.node1</span>, <span class="va">ppidf</span><span class="op">$</span><span class="va">node2</span><span class="op">)</span><span class="op">)</span>
<span class="va">ppim</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html" class="external-link">diag</a></span><span class="op">(</span><span class="fu"><a href="https://lgatto.github.io/MSnbase/reference/pSet-class.html" class="external-link">length</a></span><span class="op">(</span><span class="va">uid</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html" class="external-link">colnames</a></span><span class="op">(</span><span class="va">ppim</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html" class="external-link">rownames</a></span><span class="op">(</span><span class="va">ppim</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">uid</span>

<span class="kw">for</span> <span class="op">(</span><span class="va">k</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">ppidf</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
    <span class="va">i</span> <span class="op">&lt;-</span> <span class="va">ppidf</span><span class="op">[[</span><span class="va">k</span>, <span class="st">"X.node1"</span><span class="op">]</span><span class="op">]</span>
    <span class="va">j</span> <span class="op">&lt;-</span> <span class="va">ppidf</span><span class="op">[[</span><span class="va">k</span>, <span class="st">"node2"</span><span class="op">]</span><span class="op">]</span>
    <span class="va">ppim</span><span class="op">[</span><span class="va">i</span>, <span class="va">j</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">ppidf</span><span class="op">[[</span><span class="va">k</span>, <span class="st">"combined_score"</span><span class="op">]</span><span class="op">]</span>
<span class="op">}</span>

<span class="va">ppim</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">5</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">8</span><span class="op">]</span></code></pre></div>
<pre><code>##        NUDT5 NOP2 HSPA4 RPS13 RPL35A RPL13A CPS1 CTNNB1
## NUDT5      1    0     0     0  0.000  0.000    0      0
## NOP2       0    1     0     0  0.000  0.000    0      0
## HSPA4      0    0     1     0  0.000  0.000    0      0
## RPS13      0    0     0     1  0.997  0.998    0      0
## RPL35A     0    0     0     0  1.000  0.999    0      0</code></pre>
<p>We now have a contingency matrix reflecting a total of 19910 interactions between 1287 proteins. Below, we only keep proteins that are also available in our spatial proteomics data (renamed to <code>andyppi</code>), subset the PPI and LOPIT data, create the appropriate <code>MSnSet</code> object, and filter out proteins without any interaction scores.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">andyppi</span> <span class="op">&lt;-</span> <span class="va">andy2011</span>
<span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureNames.html" class="external-link">featureNames</a></span><span class="op">(</span><span class="va">andyppi</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/grep.html" class="external-link">sub</a></span><span class="op">(</span><span class="st">"_HUMAN"</span>, <span class="st">""</span>, <span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">andyppi</span><span class="op">)</span><span class="op">$</span><span class="va">UniProtKB.entry.name</span><span class="op">)</span>
<span class="va">cmn</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/sets.html" class="external-link">intersect</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureNames.html" class="external-link">featureNames</a></span><span class="op">(</span><span class="va">andyppi</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html" class="external-link">rownames</a></span><span class="op">(</span><span class="va">ppim</span><span class="op">)</span><span class="op">)</span>
<span class="va">ppim</span> <span class="op">&lt;-</span> <span class="va">ppim</span><span class="op">[</span><span class="va">cmn</span>, <span class="op">]</span>
<span class="va">andyppi</span> <span class="op">&lt;-</span> <span class="va">andyppi</span><span class="op">[</span><span class="va">cmn</span>, <span class="op">]</span>

<span class="va">ppi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://lgatto.github.io/MSnbase/reference/MSnSet-class.html" class="external-link">MSnSet</a></span><span class="op">(</span><span class="va">ppim</span>, fData <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">andyppi</span><span class="op">)</span>,
              pData <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html" class="external-link">data.frame</a></span><span class="op">(</span>row.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/row_colnames.html" class="external-link">colnames</a></span><span class="op">(</span><span class="va">ppim</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
<span class="va">ppi</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/filterZeroCols.html">filterZeroCols</a></span><span class="op">(</span><span class="va">ppi</span><span class="op">)</span></code></pre></div>
<pre><code>## Removing 178 columns with only 0s.</code></pre>
<p>We now have two <code>MSnSet</code> objects containing respectively 520 primary experimental protein profiles along a sub-cellular density gradient (<code>andyppi</code>) and 520 auxiliary interaction profiles (<code>ppi</code>).</p>
</div>
</div>
<div id="sec:svmtl" class="section level1">
<h1 class="hasAnchor">
<a href="#sec:svmtl" class="anchor" aria-hidden="true"></a>Support vector machine transfer learning</h1>
<p>The SVM-TL method descibed in <span class="citation">(L. M. Breckels et al. 2016)</span> has not yet been incorporated in the <em><a href="https://bioconductor.org/packages/3.13/pRoloc" class="external-link">pRoloc</a></em> package. The code implementing the method is currently available in its own repository:</p>
<p><a href="https://github.com/ComputationalProteomicsUnit/lpsvm-tl-code" class="external-link uri">https://github.com/ComputationalProteomicsUnit/lpsvm-tl-code</a></p>
</div>
<div id="sec:knntl" class="section level1">
<h1 class="hasAnchor">
<a href="#sec:knntl" class="anchor" aria-hidden="true"></a>Nearest neighbour transfer learning</h1>
<div id="sec:theopt" class="section level2">
<h2 class="hasAnchor">
<a href="#sec:theopt" class="anchor" aria-hidden="true"></a>Optimal weights</h2>
<p>The weighted nearest neighbours transfer learning algorithm estimates optimal weights for the different data sources and the spatial niches described for the data at hand with the <em>knntlOptimisation</em> function. For instance, for the human data modelled by the <code>andy2011</code> and <code>andygoset</code> objects<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> and the 10 annotated sub-cellular localisations (Golgi, Mitochondrion, PM, Lysosome, Cytosol, Cytosol/Nucleus, Nucleus, Ribosome 60S, Ribosome 40S and ER), we want to know how to optimally combine primary and auxiliary data. If we look at figure @ref(fig:andypca), that illustrates the experimental separation of the 10 spatial classes on a principal component plot, we see that some organelles such as the mitochondrion or the cytosol and cytosol/nucleus are well resolved, while others such as the Golgi or the ER are less so. In this experiment, the former classes are not expected to benefit from another data source, while the latter should benefit from additional information.</p>
<div class="figure">
<img src="v05-pRoloc-transfer-learning_files/figure-html/andypca-1.png" alt="PCA plot of `andy2011`. The multivariate protein profiles are summarised along the two first principal components. Proteins of unknown localisation are represented by empty grey points. Protein markers, which are well-known residents of specific sub-cellular niches are colour-coded and form clusters on the figure." width="700"><p class="caption">
PCA plot of <code>andy2011</code>. The multivariate protein profiles are summarised along the two first principal components. Proteins of unknown localisation are represented by empty grey points. Protein markers, which are well-known residents of specific sub-cellular niches are colour-coded and form clusters on the figure.
</p>
</div>
<p>Let’s define a set of three possible weights: 0, 0.5 and 1. A weight of 1 indicates that the final results rely exclusively on the experimental data and ignore completely the auxiliary data. A weight of 0 represents the opposite situation, where the primary data is ignored and only the auxiliary data is considered. A weight of 0.5 indicates that each data source will contribute equally to the final results. It is the algorithm’s optimisation step task to identify the optimal combination of class-specific weights for a given primary and auxiliary data pair. The optimisation process can be quite time consuming for many weights and many sub-cellular classes, as all combinations (there are <span class="math inline">\(number~of~classes^{number~of~weights}\)</span> possibilities; see below). One would generally defined more weights (for example 0, 0.25, 0.5, 0.75, 1 or 0, 0.33, 0.67, 1) to explore more fine-grained integration opportunities. The possible weight combinations can be calculated with the <em>thetas</em> function:</p>
<ul>
<li>3 classes, 3 weights</li>
</ul>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">head</a></span><span class="op">(</span><span class="fu"><a href="../reference/thetas.html">thetas</a></span><span class="op">(</span><span class="fl">3</span>, by <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## Weigths:
##   (0, 0.5, 1)</code></pre>
<pre><code>##      [,1] [,2] [,3]
## [1,]    0  0.0  0.0
## [2,]    0  0.0  0.5
## [3,]    0  0.0  1.0
## [4,]    0  0.5  0.0
## [5,]    0  0.5  0.5
## [6,]    0  0.5  1.0</code></pre>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://lgatto.github.io/MSnbase/reference/pSet-class.html" class="external-link">dim</a></span><span class="op">(</span><span class="fu"><a href="../reference/thetas.html">thetas</a></span><span class="op">(</span><span class="fl">3</span>, by <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## Weigths:
##   (0, 0.5, 1)</code></pre>
<pre><code>## [1] 27  3</code></pre>
<ul>
<li>5 classes, 4 weights</li>
</ul>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://lgatto.github.io/MSnbase/reference/pSet-class.html" class="external-link">dim</a></span><span class="op">(</span><span class="fu"><a href="../reference/thetas.html">thetas</a></span><span class="op">(</span><span class="fl">5</span>, length.out <span class="op">=</span> <span class="fl">4</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## Weigths:
##   (0, 0.333333333333333, 0.666666666666667, 1)</code></pre>
<pre><code>## [1] 1024    5</code></pre>
<ul>
<li>for the human <code>andy2011</code> data, considering 4 weights, there are very many combinations:</li>
</ul>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## marker classes for andy2011</span>
<span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/unique.html" class="external-link">unique</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">andy2011</span><span class="op">)</span><span class="op">$</span><span class="va">markers.tl</span><span class="op">)</span>
<span class="va">m</span> <span class="op">&lt;-</span> <span class="va">m</span><span class="op">[</span><span class="va">m</span> <span class="op">!=</span> <span class="st">"unknown"</span><span class="op">]</span>
<span class="va">th</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/thetas.html">thetas</a></span><span class="op">(</span><span class="fu"><a href="https://lgatto.github.io/MSnbase/reference/pSet-class.html" class="external-link">length</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span>, length.out<span class="op">=</span><span class="fl">4</span><span class="op">)</span></code></pre></div>
<pre><code>## Weigths:
##   (0, 0.333333333333333, 0.666666666666667, 1)</code></pre>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://lgatto.github.io/MSnbase/reference/pSet-class.html" class="external-link">dim</a></span><span class="op">(</span><span class="va">th</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1048576      10</code></pre>
<p>The actual combination of weights to be tested can be defined in multiple ways: by passing a weights matrix explicitly (as those generated with <em>thetas</em> above) through the <code>th</code> argument; or by defining the increment between weights using <code>by</code>; or by specifying the number of weights to be used through the <code>length.out</code> argument.</p>
<p>Considering the sub-cellular resolution for this experiment, we would anticipate that the mitochondrion, the cytosol and the cytosol/nucleus classes would get high weights, while the ER and Golgi would be assigned lower weights.</p>
<p>As we use a nearest neighbour classifier, we also need to know how many neighbours to consider when classifying a protein of unknown localisation. The <em>knnOptimisation</em> function (see the <em>pRoloc-tutorial</em> vignette and the functions manual page) can be run on the primary and auxiliary data sources independently to estimate the best <span class="math inline">\(k_P\)</span> and <span class="math inline">\(k_A\)</span> values. Here, based on <em>knnOptimisation</em>, we use 3 and 3, for <span class="math inline">\(k_P\)</span> and <span class="math inline">\(k_A\)</span> respectively.</p>
<p>Finally, to assess the validity of the weight selection, it should be repeated a certain number of times (default value is 50). As the weight optimisation can become very time consuming for a wide range of weights and many target classes, we would recommend to start with a lower number of iterations, pre-analyse the results, proceed with further iterations and eventually combine the optimisation results data with the <em>combineThetaRegRes</em> function before proceeding with the selection of best weights.</p>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">topt</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/knntlOptimisation.html">knntlOptimisation</a></span><span class="op">(</span><span class="va">andy2011</span>, <span class="va">andygoset</span>,
                          th <span class="op">=</span> <span class="va">th</span>,
                          k <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>,
                          fcol <span class="op">=</span> <span class="st">"markers.tl"</span>,
                          times <span class="op">=</span> <span class="fl">50</span><span class="op">)</span></code></pre></div>
<p>The above code chunk would take too much time to be executed in the frame of this vignette. Below, we pass a very small subset of theta matrix to minimise the computation time. The <em>knntlOptimisation</em> function supports parallelised execution using various backends thanks to the <em><a href="https://bioconductor.org/packages/3.13/BiocParallel" class="external-link">BiocParallel</a></em> package; an appropriate backend will be defined automatically according to the underlying architecture and user-defined backends can be defined through the <code>BPPARAM</code> argument<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>. Also, in the interest of time, the weights optimisation is repeated only 5 times below.</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html" class="external-link">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span>
<span class="va">i</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html" class="external-link">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/BiocGenerics/man/nrow.html" class="external-link">nrow</a></span><span class="op">(</span><span class="va">th</span><span class="op">)</span>, <span class="fl">12</span><span class="op">)</span>
<span class="va">topt</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/knntlOptimisation.html">knntlOptimisation</a></span><span class="op">(</span><span class="va">andy2011</span>, <span class="va">andygoset</span>,
                          th <span class="op">=</span> <span class="va">th</span><span class="op">[</span><span class="va">i</span>, <span class="op">]</span>,
                          k <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>,
                          fcol <span class="op">=</span> <span class="st">"markers.tl"</span>,
                          times <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## Removing 481 columns with only 0s.</code></pre>
<pre><code>## Note: vector will be ordered according to classes: Cytosol Cytosol/Nucleus ER Golgi Lysosome Mitochondrion Nucleus PM Ribosome 40S Ribosome 60S (as names are not explicitly defined)</code></pre>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">topt</span></code></pre></div>
<pre><code>## Object of class "ThetaRegRes"
## Algorithm: theta 
## Theta hyper-parameters:
##  weights: 0 0.3333333 0.6666667 1 
##  k: 3 3 
##  nrow: 12 
## Design:
##  Replication: 5 x 5-fold X-validation
##  Partitioning: 0.2/0.8 (test/train)
## Results
##  macro F1:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.8135  0.8644  0.8850  0.8773  0.9042  0.9192 
##  best theta:
##             Cytosol Cytosol.Nucleus ER Golgi Lysosome Mitochondrion Nucleus PM
## weight:0          0               0  4     4        0             0       2  1
## weight:0.33       0               4  0     0        1             1       0  3
## weight:0.67       2               1  0     1        0             0       0  0
## weight:1          3               0  1     0        4             4       3  1
##             Ribosome.40S Ribosome.60S
## weight:0               4            0
## weight:0.33            1            3
## weight:0.67            0            2
## weight:1               0            0</code></pre>
<p>The optimisation is performed on the labelled marker examples only. When removing unlabelled non-marker proteins (the <code>unknowns</code>), some auxiliary GO columns end up containing only 0 (the GO-protein association was only observed in non-marker proteins), which are temporarily removed.</p>
<p>The <code>topt</code> result stores all the result from the optimisation step, and in particular the observed theta weights, which can be directly plotted as shown on the <a href="#fig:bubble">bubble plot</a> below. These bubble plots give the proportion of best weights for each marker class that was observed during the optimisation phase. We see that the mitochondrion, the cytosol and cytosol/nucleus classes predominantly are scored with height weights (2/3 and 1), consistent with high reliability of the primary data. The Golgi and the ribosomal clusters (and to a lesser extend the ER) favour smaller scores, indicating a substantial benefit of the auxiliary data.</p>
<div class="figure">
<img src="Figures/bubble-andy.png" id="fig:bubble" alt=""><p class="caption">Results obtained from an extensive optimisation on the primary <code>andy2011</code> and auxiliary <code>andygoset</code> data sets, as produced by <code>plot(topt)</code>. This figure is not the result for the previous code chunk, where only a random subset of 10 candidate weights have been tested.</p>
</div>
</div>
<div id="sec:choosep" class="section level2">
<h2 class="hasAnchor">
<a href="#sec:choosep" class="anchor" aria-hidden="true"></a>Choosing weights</h2>
<p>A set of best weights must be chosen and applied to the classification of the unlabelled proteins (formally annotated as <code>unknown</code>). These can be defined manually, based on the pattern observed in the weights <a href="#fig:bubble">bubble plot</a>, or automatically extracted with the <em>getParams</em> method<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>. See <em>?getParams</em> for details and the <em>favourPrimary</em> function, if it is desirable to systematically favour the primary data (i.e. high weights) when different weight combinations perform equally well.</p>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/GenRegRes-class.html">getParams</a></span><span class="op">(</span><span class="va">topt</span><span class="op">)</span></code></pre></div>
<pre><code>##         Cytosol Cytosol/Nucleus              ER           Golgi        Lysosome 
##       1.0000000       0.3333333       0.0000000       0.0000000       1.0000000 
##   Mitochondrion         Nucleus              PM    Ribosome 40S    Ribosome 60S 
##       1.0000000       1.0000000       0.3333333       0.0000000       0.3333333</code></pre>
<p>We provide the best parameters for the extensive parameter optimisation search, as provided by <em>getParams</em>:</p>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="op">(</span><span class="va">bw</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/abstract.html" class="external-link">experimentData</a></span><span class="op">(</span><span class="va">andy2011</span><span class="op">)</span><span class="op">@</span><span class="va">other</span><span class="op">$</span><span class="va">knntl</span><span class="op">$</span><span class="va">thetas</span><span class="op">)</span></code></pre></div>
<pre><code>##         Cytosol Cytosol/Nucleus              ER           Golgi        Lysosome 
##       0.6666667       0.6666667       0.3333333       0.3333333       0.6666667 
##   Mitochondrion         Nucleus              PM    Ribosome 40S    Ribosome 60S 
##       0.6666667       0.3333333       0.3333333       0.0000000       0.3333333</code></pre>
</div>
<div id="sec:thclass" class="section level2">
<h2 class="hasAnchor">
<a href="#sec:thclass" class="anchor" aria-hidden="true"></a>Applying best <em>theta</em> weights</h2>
<p>To apply our best weights and learn from the auxiliary data accordingly when classifying the unlabelled proteins to one of the sub-cellular niches considered in <code>markers.tl</code> (as displayed on figure @ref(fig:andypca)), we pass the primary and auxiliary data sets, best weights, best k’s (and, on our case the marker’s feature variable we want to use, default would be <code>markers</code>) to the <em>knntlClassification</em> function.</p>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">andy2011</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/knntlClassification.html">knntlClassification</a></span><span class="op">(</span><span class="va">andy2011</span>, <span class="va">andygoset</span>,
                                bestTheta <span class="op">=</span> <span class="va">bw</span>,
                                k <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/S4Vectors/man/Vector-class.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span>,
                                fcol <span class="op">=</span> <span class="st">"markers.tl"</span><span class="op">)</span></code></pre></div>
<p>This will generate a new instance of class <em>MSnSet</em>, identical to the primary data, including the classification results and classifications scores of the transfer learning classification algorithm (as <code>knntl</code> and <code>knntl.scores</code> feature variables respectively). Below, we extract the former with the <em>getPrediction</em> function and plot the results of the classification.</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">andy2011</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/getPredictions.html">getPredictions</a></span><span class="op">(</span><span class="va">andy2011</span>, fcol <span class="op">=</span> <span class="st">"knntl"</span><span class="op">)</span></code></pre></div>
<pre><code>## ans
## Chromatin associated              Cytosol      Cytosol/Nucleus 
##                   11                  293                   45 
##             Endosome                   ER                Golgi 
##                   12                  189                   69 
##             Lysosome        Mitochondrion              Nucleus 
##                   64                  253                  117 
##                   PM         Ribosome 40S         Ribosome 60S 
##                  241                   19                   58</code></pre>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/getStockcol.html">setStockcol</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html" class="external-link">paste0</a></span><span class="op">(</span><span class="fu"><a href="../reference/getStockcol.html">getStockcol</a></span><span class="op">(</span><span class="op">)</span>, <span class="st">"80"</span><span class="op">)</span><span class="op">)</span>
<span class="va">ptsze</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html" class="external-link">exp</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/Biobase/man/featureData.html" class="external-link">fData</a></span><span class="op">(</span><span class="va">andy2011</span><span class="op">)</span><span class="op">$</span><span class="va">knntl.scores</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span>
<span class="fu"><a href="../reference/plot2D.html">plot2D</a></span><span class="op">(</span><span class="va">andy2011</span>, fcol <span class="op">=</span> <span class="st">"knntl"</span>, cex <span class="op">=</span> <span class="va">ptsze</span><span class="op">)</span>
<span class="fu"><a href="../reference/getStockcol.html">setStockcol</a></span><span class="op">(</span><span class="cn">NULL</span><span class="op">)</span>
<span class="fu"><a href="../reference/addLegend.html">addLegend</a></span><span class="op">(</span><span class="va">andy2011</span>, where <span class="op">=</span> <span class="st">"topright"</span>,
          fcol <span class="op">=</span> <span class="st">"markers.tl"</span>,
          bty <span class="op">=</span> <span class="st">"n"</span>, cex <span class="op">=</span> <span class="fl">.7</span><span class="op">)</span></code></pre></div>
<div class="figure">
<img src="v05-pRoloc-transfer-learning_files/figure-html/andypca2-1.png" alt="PCA plot of `andy2011` after transfer learning classification. The size of the points is proportional to the classification scores." width="576"><p class="caption">
PCA plot of <code>andy2011</code> after transfer learning classification. The size of the points is proportional to the classification scores.
</p>
</div>
<p>Please read the <em>pRoloc-tutorial</em> vignette, and in particular the classification section, for more details on how to proceed with exploration the classification results and classification scores.</p>
</div>
</div>
<div id="sec:ccl" class="section level1">
<h1 class="hasAnchor">
<a href="#sec:ccl" class="anchor" aria-hidden="true"></a>Conclusions</h1>
<p>This vignette describes the application of a weighted <span class="math inline">\(k\)</span>-nearest neighbour transfer learning algorithm and its application to the sub-cellular localisation prediction of proteins using quantitative proteomics data as primary data and Gene Ontology-derived binary data as auxiliary data source. The algorithm can be used with various data sources (we show how to compile binary data from the Human Protein Atlas in section @ref(sec:hpaaux)) and have successfully applied the algorithm <span class="citation">(L. M. Breckels et al. 2016)</span> on third-party quantitative auxiliary data.</p>
</div>
<div id="session-information" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#session-information" class="anchor" aria-hidden="true"></a>Session information</h1>
<p>All software and respective versions used to produce this document are listed below.</p>
<pre><code>## R Under development (unstable) (2021-04-15 r80175)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 20.04.2 LTS
## 
## Matrix products: default
## BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats4    parallel  stats     graphics  grDevices utils     datasets 
## [8] methods   base     
## 
## other attached packages:
##  [1] hpar_1.33.3          biomaRt_2.47.8       class_7.3-18        
##  [4] pRolocdata_1.29.0    pRoloc_1.31.2        BiocParallel_1.25.5 
##  [7] MLInterfaces_1.71.2  cluster_2.1.1        annotate_1.69.2     
## [10] XML_3.99-0.6         AnnotationDbi_1.53.1 IRanges_2.25.10     
## [13] MSnbase_2.17.7       ProtGenerics_1.23.9  S4Vectors_0.29.17   
## [16] mzR_2.25.4           Rcpp_1.0.6           Biobase_2.51.0      
## [19] BiocGenerics_0.37.4  knitr_1.33           BiocStyle_2.19.2    
## 
## loaded via a namespace (and not attached):
##   [1] BiocFileCache_1.99.7  systemfonts_1.0.1     plyr_1.8.6           
##   [4] splines_4.1.0         ggplot2_3.3.3         digest_0.6.27        
##   [7] foreach_1.5.1         htmltools_0.5.1.1     viridis_0.6.0        
##  [10] fansi_0.4.2           magrittr_2.0.1        memoise_2.0.0        
##  [13] doParallel_1.0.16     mixtools_1.2.0        limma_3.47.12        
##  [16] recipes_0.1.16        Biostrings_2.59.2     gower_0.2.2          
##  [19] pkgdown_1.6.1.9001    lpSolve_5.6.15        prettyunits_1.1.1    
##  [22] colorspace_2.0-0      blob_1.2.1            rappdirs_0.3.3       
##  [25] textshaping_0.3.3     xfun_0.22             dplyr_1.0.5          
##  [28] crayon_1.4.1          jsonlite_1.7.2        hexbin_1.28.2        
##  [31] impute_1.65.0         survival_3.2-10       iterators_1.0.13     
##  [34] glue_1.4.2            gtable_0.3.0          ipred_0.9-11         
##  [37] zlibbioc_1.37.0       XVector_0.31.1        kernlab_0.9-29       
##  [40] scales_1.1.1          vsn_3.59.1            mvtnorm_1.1-1        
##  [43] DBI_1.1.1             viridisLite_0.4.0     xtable_1.8-4         
##  [46] progress_1.2.2        clue_0.3-59           bit_4.0.4            
##  [49] proxy_0.4-25          mclust_5.4.7          preprocessCore_1.53.2
##  [52] MsCoreUtils_1.3.3     lava_1.6.9            prodlim_2019.11.13   
##  [55] sampling_2.9          httr_1.4.2            FNN_1.1.3            
##  [58] RColorBrewer_1.1-2    ellipsis_0.3.2        pkgconfig_2.0.3      
##  [61] nnet_7.3-15           sass_0.3.1            dbplyr_2.1.1         
##  [64] utf8_1.2.1            caret_6.0-86          tidyselect_1.1.1     
##  [67] rlang_0.4.11          reshape2_1.4.4        munsell_0.5.0        
##  [70] tools_4.1.0           LaplacesDemon_16.1.4  cachem_1.0.4         
##  [73] generics_0.1.0        RSQLite_2.2.7         evaluate_0.14        
##  [76] stringr_1.4.0         fastmap_1.1.0         mzID_1.29.0          
##  [79] yaml_2.2.1            ragg_1.1.2            ModelMetrics_1.2.2.2 
##  [82] bit64_4.0.5           fs_1.5.0              randomForest_4.6-14  
##  [85] purrr_0.3.4           KEGGREST_1.31.1       dendextend_1.14.0    
##  [88] ncdf4_1.17            nlme_3.1-152          xml2_1.3.2           
##  [91] compiler_4.1.0        filelock_1.0.2        curl_4.3.1           
##  [94] png_0.1-7             e1071_1.7-6           affyio_1.61.0        
##  [97] tibble_3.1.1          bslib_0.2.4           stringi_1.5.3        
## [100] highr_0.9             desc_1.3.0            lattice_0.20-41      
## [103] Matrix_1.3-2          vctrs_0.3.8           pillar_1.6.0         
## [106] lifecycle_1.0.0       BiocManager_1.30.12   jquerylib_0.1.4      
## [109] MALDIquant_1.19.3     data.table_1.14.0     R6_2.5.0             
## [112] pcaMethods_1.83.0     affy_1.69.1           bookdown_0.22        
## [115] gridExtra_2.3         codetools_0.2-18      gtools_3.8.2         
## [118] MASS_7.3-53.1         assertthat_0.2.1      rprojroot_2.0.2      
## [121] withr_2.4.2           hms_1.0.0             grid_4.1.0           
## [124] rpart_4.1-15          timeDate_3043.102     coda_0.19-4          
## [127] rmarkdown_2.7         segmented_1.3-4       pROC_1.17.0.1        
## [130] lubridate_1.7.10</code></pre>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor" aria-hidden="true"></a>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Ashburner:2000" class="csl-entry">
Ashburner, M, C A Ball, J A Blake, D Botstein, H Butler, J M Cherry, A P Davis, et al. 2000. <span>“Gene Ontology: Tool for the Unification of Biology. The Gene Ontology Consortium.”</span> <em>Nat Genet</em> 25 (1): 25–29. <a href="https://doi.org/10.1038/75556" class="external-link">https://doi.org/10.1038/75556</a>.
</div>
<div id="ref-Breckels:2016" class="csl-entry">
Breckels, L M, S B Holden, D Wojnar, C M Mulvey, A Christoforou, A Groen, M W Trotter, O Kohlbacher, K S Lilley, and L Gatto. 2016. <span>“Learning from Heterogeneous Data Sources: An Application in Spatial Proteomics.”</span> <em>PLoS Comput Biol</em> 12 (5): e1004920. <a href="https://doi.org/10.1371/journal.pcbi.1004920" class="external-link">https://doi.org/10.1371/journal.pcbi.1004920</a>.
</div>
<div id="ref-Breckels2013" class="csl-entry">
Breckels, Lisa M, Laurent Gatto, Andy Christoforou, Arnoud J Groen, Kathryn S Lilley, and Matthew W B Trotter. 2013. <span>“The Effect of Organelle Discovery Upon Sub-Cellular Protein Localisation.”</span> <em>J Proteomics</em>, March. <a href="https://doi.org/10.1016/j.jprot.2013.02.019" class="external-link">https://doi.org/10.1016/j.jprot.2013.02.019</a>.
</div>
<div id="ref-Christoforou:2016" class="csl-entry">
Christoforou, A, C M Mulvey, L M Breckels, A Geladaki, T Hurrell, P C Hayward, T Naake, et al. 2016. <span>“A Draft Map of the Mouse Pluripotent Stem Cell Spatial Proteome.”</span> <em>Nat Commun</em> 7: 8992. <a href="https://doi.org/10.1038/ncomms9992" class="external-link">https://doi.org/10.1038/ncomms9992</a>.
</div>
<div id="ref-Gatto2010" class="csl-entry">
Gatto, Laurent, Juan Antonio Vizcaíno, Henning Hermjakob, Wolfgang Huber, and Kathryn S Lilley. 2010. <span>“Organelle Proteomics Experimental Designs and Analysis.”</span> <em>Proteomics</em>. <a href="https://doi.org/10.1002/pmic.201000244" class="external-link">https://doi.org/10.1002/pmic.201000244</a>.
</div>
<div id="ref-Uhlen:2010" class="csl-entry">
Uhlen, Mathias, Per Oksvold, Linn Fagerberg, Emma Lundberg, Kalle Jonasson, Mattias Forsberg, Martin Zwahlen, et al. 2010. <span>“<span class="nocase">Towards a knowledge-based Human Protein Atlas.</span>”</span> <em>Nature Biotechnology</em> 28 (12): 1248–50. <a href="https://doi.org/10.1038/nbt1210-1248" class="external-link">https://doi.org/10.1038/nbt1210-1248</a>.
</div>
</div>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>We will use the sub-cellular markers defined in the <code>markers.tl</code> feature variable, instead of the default <code>markers</code>.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Large scale applications of this algorithms were run on a cluster using an MPI backend defined with <code>SnowParams(256, type="MPI")</code>.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Note that the scores extracted here are based on the random subsest of weights.<a href="#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p></p>
<p>Developed by Laurent Gatto, Lisa Breckels, Oliver Crook.</p>
</div>

<div class="pkgdown">
  <p></p>
<p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link external-link">pkgdown</a> 1.6.1.9001.</p>
</div>

      </footer>
</div>

  


  

  </body>
</html>
