.pRolocEnv <- new.env(parent=emptyenv(), hash=TRUE)

## plotting stock colors and point chars
stockcol <-  c(brewer.pal(9, "Set1"),
               "#333333", ## grey20
               "#A021EF", ## purple
               "#008A45", ## springgreen4
               "#00008A", ## blue4
               "#FF6347") ## tomato
assign("stockcol", stockcol, envir = .pRolocEnv)
getStockcol <- function() get("stockcol", envir=.pRolocEnv)

stockpch <- c(15, 17,19, 18, 23:25, 7, 9, 13, 3:4,  8)
assign("stockpch", stockpch, envir = .pRolocEnv)
getStockpch <- function() get("stockpch", envir=.pRolocEnv)


unknowncol <- "#E7E7E7" ## grey91
assign("unknowncol", unknowncol, envir = .pRolocEnv)
getUnknowncol <- function() get("unknowncol", envir=.pRolocEnv)


unknownpch <- 21
assign("unknownpch", unknownpch, envir = .pRolocEnv)
getUnknownpch <- function() get("unknownpch", envir=.pRolocEnv)

## these rda files have been generated by inst/scripts/biomaRt.R
load(dir(system.file(package="pRoloc", dir="extdata"),
         full.name=TRUE,
         pattern="attrList"))

load(dir(system.file(package="pRoloc", dir="extdata"),
         full.name=TRUE,
         pattern="filterList"))

load(dir(system.file(package="pRoloc", dir="extdata"),
         full.name=TRUE,
         pattern="martTab"))

assign("attrList", attrList, envir = .pRolocEnv)
assign("filterList", filterList, envir = .pRolocEnv)
assign("martTab", martTab, envir = .pRolocEnv)

filtersOfInterest <- c("ensembl_gene_id",
                       "ensembl_transcript_id",
                       "ensembl_peptide_id",
                       "ensembl_exon_id",
                       "wikigene_id",
                       "wikigene_name",
                       "embl",
                       "entrezgene",
                       "hgnc_id",
                       "hgnc_symbol",
                       "ipi",
                       "protein_id",
                       "refseq_dna",
                       "refseq_mrna",
                       "refseq_peptide",
                       "refseq_genomic",
                       "ottt",
                       "ottg",
                       "ucsc",
                       "uniprot_sptrembl",
                       "uniprot_swissprot",
                       "uniprot_swissprot_accession",
                       "unigene",
                       "geneindex",
                       "tair_locus",
                       "tair_locus_model",
                       "tair_symbol",
                       "uniprot_genename",
                       "flybase_annotation_id",
                       "flybase_gene_id",
                       "flybase_transcript_id",
                       "flybase_translation_id",
                       "flybasename_gene",
                       "flybasename_transcript",
                       "flybasename_translation",
                       "sgd",
                       "sgd_gene",
                       "sgd_transcript")
assign("filtersOfInterest", filtersOfInterest, envir=.pRolocEnv)

attributesOfInterest <- c("ensembl_gene_id",
                          "ensembl_peptide_id",
                          "ensembl_transcript_id",
                          ## GO
                          "go_id", "go_accession",
                          "namespace_1003","name_1006",                          
                          "go_linkage_type",
                          ## sequences
                          "cdna", "peptide",
                          "gene_exon", "gene_exon_intron",
                            "transcript_exon_intron",
                          "coding")
assign("attributesOfInterest", attributesOfInterest, envir=.pRolocEnv)

GOEvidenceCodes <- c("EXP", ## experimental evidence
                     "IDA", "IPI", "IMP", "IGI", "IEP", 
                     "ISS", ## computational analysis evidence
                     "ISO", "ISA", "ISM", "IGC", "IBA", 
                     "IBD", "IKR", "IRD", "RCA",
                     ## author statement - traceable or non-traceable
                     "TAS", "NAS",
                     ## curator statement - inferred by of no data
                     "IC", "ND",
                     ## obsolete - not recorded
                     "NR")
assign("GOEvidenceCodes", GOEvidenceCodes, envir = .pRolocEnv)

GONamespace <- c("biological_process", "cellular_component", "molecular_function")
assign("GONamespace", GONamespace, envir = .pRolocEnv)

## Default params is NULL - initialised by pRoloc::setAnnotationParams()
assign("params", NULL, envir=.pRolocEnv)

## Default is NULL - initialised by first call to pRoloc:::getGOlist()
assign("GOlist", NULL, envir=.pRolocEnv)


orgcols <-
  data.frame(rbind(c('GO:0030136', 'clathrin-coated vesicle', 'tomato3'),
                   c('GO:0009507', 'chloroplast', 'pink'),
                   c('GO:0030137', 'COPI-coated vesicle', 'turquoise'),
                   c('GO:0030134', 'ER to Golgi transport vesicle (COPII-coated vesicle)', 'turquoise4'),
                   c('GO:0005783', 'endoplasmic reticulum', 'green'),
                   c('GO:0005794', 'Golgi apparatus', 'blue'),
                   c('GO:0005739', 'mitochondrion', 'purple'),
                   c('GO:0005777', 'peroxisome', 'maroon'),
                   c('GO:0005886', 'plasma membrane', 'yellow'),
                   c('GO:0005770', 'late endosome (PVC)', 'orange'),
                   c('GO:0030904', 'retromer complex', 'tan'),
                   c('GO:0005802', 'trans-Golgi network', 'black'),
                   c('GO:0005773', 'vacuole', 'red'),
                   c('GO:0005634', 'nucleus', 'steelblue'),
                   c('GO:0005730', 'nucleolus', 'midnightblue'),
                   c('GO:0005764', 'lysosome', 'darkgreen'),
                   c('GO:0005840', 'ribosome', 'yellow4')
                   ))
## BIG = col2hcl("yellowgreen"),
colnames(orgcols) <- c("GOId","Description", "Colour")

assign("orgcols", orgcols, envir = .pRolocEnv)


## Setting topGO's GO[CC|MF|BP]Term environments
topGO::groupGOTerms(where = .pRolocEnv)

lockEnvironment(.pRolocEnv,bindings=TRUE)




###################################
## .pRolco envir accessor function
getGONamespace <- function() get("GONamespace", envir=.pRolocEnv)
getGOEvidenceCodes <- function() get("GOEvidenceCodes", envir=.pRolocEnv)
getAttrList <- function() get("attrList", envir=.pRolocEnv)
getFilterList <- function() get("filterList", envir=.pRolocEnv)
getMartTab <- function() get("martTab", envir=.pRolocEnv)
getFiltersOfInterest <- function() get("filtersOfInterest", envir=.pRolocEnv)

getGOlist <- function() {
  GOlist <- get("GOlist", envir = .pRolocEnv)
  if (is.null(GOlist)) {
    message("Loading all GO Terms...")
    GOlist <- as.list(GOTERM)
    unlockBinding("GOlist", .pRolocEnv)
    assign("GOlist", GOlist, envir=.pRolocEnv)
    lockBinding("GOlist", .pRolocEnv)
  }
  return(GOlist)
}

##' This function gives the attributes that are used
##' as a criterion for ENSEMBL data sets to be used
##' in pRoloc. These are the attributes that are
##' susceptible to be queried by pRoloc functions
##' as \code{\link{getGO}} or \code{\link{getSeq}}.
##'
##' @title Get Biomart attributes of interest.
##' @return A \code{character} with the attributes
##' that the biomart data sets used in pRoloc all have.
##' @author Laurent Gatto 
##' @export
getAttributesOfInterest <- function() get("attributesOfInterest", envir=.pRolocEnv)

getAnnotationParams <- function() get("params", envir=.pRolocEnv)

getOrgCols <- function() get("orgcols", envir=.pRolocEnv)
