# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvtCpp <- function(X_, mu_, sigma_, df_, log_, ncores_, isChol_) {
    .Call('_pRoloc_dmvtCpp', PACKAGE = 'pRoloc', X_, mu_, sigma_, df_, log_, ncores_, isChol_)
}

