# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  Copyright (C) 2014 Matteo Fasiolo  matteo.fasiolo@gmail.com
#'This program is free software; you can redistribute it and/or
#' modify it under the terms of the GNU General Public License
#' as published by the Free Software Foundation; either version 2
#' of the License, or (at your option) any later version.
#' This program is distributed in the hope that it will be useful,
#' but WITHOUT ANY WARRANTY; without even the implied warranty of
#' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#' GNU General Public License for more details.
#' (www.gnu.org/copyleft/gpl.html)
#' You should have received a copy of the GNU General Public License
#' along with this program; if not, write to the Free Software
#' Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
#' USA. */
NULL

dmvtCpp <- function(X_, mu_, sigma_, df_, log_, ncores_, isChol_) {
    .Call('_pRoloc_dmvtCpp', PACKAGE = 'pRoloc', X_, mu_, sigma_, df_, log_, ncores_, isChol_)
}

